---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-airtable
---
# Secret 'github-token' must be created manually:
# kubectl create secret generic github-token -n mcp-airtable --from-literal=token=<YOUR_GITHUB_TOKEN>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-airtable
  template:
    metadata:
      labels:
        app: mcp-airtable
    spec:
      containers:
        - name: mcp-airtable
          image: node:20-alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache git &&
              npm install -g https://${GITHUB_TOKEN}@github.com/delta-and-beta/mcp-airtable.git &&
              node /usr/local/lib/node_modules/mcp-airtable/dist/server.js
          ports:
            - containerPort: 3000
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: mcp-airtable
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - mcp-airtable
  rules:
    - host: mcp-airtable
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-airtable
                port:
                  number: 3000
