---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-airtable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mcp-airtable
  template:
    metadata:
      labels:
        app: mcp-airtable
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-node-01
      containers:
        - name: mcp-airtable
          image: node:20-alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache git &&
              git clone https://github.com/delta-and-beta/mcp-airtable.git /app &&
              cd /app &&
              # Patch server to bind to 0.0.0.0 for k8s
              sed -i 's/httpStream: {/httpStream: { host: "0.0.0.0",/' src/server.ts &&
              npm install --include=dev &&
              ./node_modules/.bin/tsc --skipLibCheck &&
              npm start
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: mcp-airtable
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - mcp-airtable
  rules:
    - host: mcp-airtable
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-airtable
                port:
                  number: 3000
