---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-airtable
---
# Watch upstream repo for changes (every 5 min)
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mcp-airtable-upstream
  namespace: mcp-airtable
spec:
  interval: 5m
  url: https://github.com/delta-and-beta/mcp-airtable
  ref:
    branch: main
---
# ServiceAccount for the restart job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-restarter
  namespace: mcp-airtable
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restarter
  namespace: mcp-airtable
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restarter
  namespace: mcp-airtable
subjects:
  - kind: ServiceAccount
    name: deployment-restarter
    namespace: mcp-airtable
roleRef:
  kind: Role
  name: deployment-restarter
  apiGroup: rbac.authorization.k8s.io
---
# CronJob to check for upstream changes and restart if needed
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcp-airtable-auto-update
  namespace: mcp-airtable
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-restarter
          containers:
            - name: restarter
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  # Get current upstream commit from GitRepository
                  UPSTREAM_REV=$(kubectl get gitrepository mcp-airtable-upstream -n mcp-airtable -o jsonpath='{.status.artifact.revision}' | cut -d'/' -f2 | cut -c1-7)

                  # Get current deployment annotation
                  DEPLOY_REV=$(kubectl get deployment mcp-airtable -n mcp-airtable -o jsonpath='{.spec.template.metadata.annotations.upstream-revision}' 2>/dev/null || echo "none")

                  echo "Upstream: $UPSTREAM_REV, Deployment: $DEPLOY_REV"

                  if [ "$UPSTREAM_REV" != "$DEPLOY_REV" ] && [ -n "$UPSTREAM_REV" ]; then
                    echo "New version detected, restarting deployment..."
                    kubectl patch deployment mcp-airtable -n mcp-airtable \
                      -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"upstream-revision\":\"$UPSTREAM_REV\"}}}}}"
                  else
                    echo "No changes detected"
                  fi
          restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mcp-airtable
  template:
    metadata:
      labels:
        app: mcp-airtable
      annotations:
        upstream-revision: "initial"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-node-01
      containers:
        - name: mcp-airtable
          image: node:20-alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache git &&
              git clone https://github.com/delta-and-beta/mcp-airtable.git /app &&
              cd /app &&
              npm install --include=dev &&
              npm run build &&
              npm start
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: mcp-airtable
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-airtable
  namespace: mcp-airtable
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - mcp-airtable
  rules:
    - host: mcp-airtable
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-airtable
                port:
                  number: 3000
