---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-postgres-data
  namespace: miniflux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 2Gi
---
# PostgreSQL Database with local-path storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-postgres
  namespace: miniflux
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: miniflux-postgres
  template:
    metadata:
      labels:
        app: miniflux-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "miniflux"
            - name: POSTGRES_PASSWORD
              value: "miniflux-secret"
            - name: POSTGRES_DB
              value: "miniflux"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: miniflux-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-postgres
  namespace: miniflux
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: miniflux-postgres
---
# Miniflux RSS Reader
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z miniflux-postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: miniflux
          image: miniflux/miniflux:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://miniflux:miniflux-secret@miniflux-postgres:5432/miniflux?sslmode=disable"
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "changeme123"
            - name: BASE_URL
              value: "https://miniflux.marchi.app"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: miniflux
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux
  namespace: miniflux
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: miniflux.marchi.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miniflux
                port:
                  number: 8080
